### ISSUE TITLE
Possible problem with recipient placeholders

### ISSUE THREAD

**Issue by BlitzOffline** [HelpChat/ChatChat#14]
I can't test at this moment but if I understand this right, We're passing an entire string here https://github.com/HelpChat/ChatChat/blob/2e756cf4698b5c44b86b22446d74cef2a6db705f/plugin/src/main/java/at/helpch/chatchat/util/FormatUtils.java#L43 and the parser method will only remove the first 11 characters and append a % at the start then attempt to parse the placeholders.

This means in a part that looks something like this "hello, this test %recipient_placeholder-here%" would become " test %%recipient_placeholder-here%"

**Comment by Kqliber** [comment]
While the replaceRecipientPlaceholder method does suck, this should still parse correctly as we are substringing from %recipient_, this means that when we replace this string, we are given %placeholder_here%, instead of %%placeholder_here%.

As discussed on discord, this method should be reworked as currently it probably only works if the string given only contains the recipient placeholder format, and nothing else. Not only this, but it should be reworked to support multiple recipient placeholders

**Comment by Starmism** [comment]
Fixed with #15
