### ISSUE TITLE
Discord SRV Hook

### ISSUE THREAD

**Issue by KieranMP** [HelpChat/ChatChat#219]
Hey there! I am using the latest snapshot (71) of ChatChat (see dump below). I am also using the latest dev build of DiscordSRV.

I am having troubles with the DiscordSRVHook. Every time a message is sent in MC, DiscordSRV debugger says "chat message received" twice, one for global, and one for the channel the player is in. Then, two messages are sent to discord. Why is this happening?

I have checked. This issue stops when I remove ChatChat from the server.

https://paste.helpch.at/miyazukunu

**Comment by MiguVT** [comment]
I found a fix, it looks like it's a discordsrv problem, you can fix it doing something like it in the config of discordsrv:
Channels: {"global": "", "default": "1214158512842874940", "staff": "1214139129177182258"}

**Comment by BlitzOffline** [comment]
Closing this because MiguVT's answer seems to check out. You can try their solution. You have to have the same channel names in DiscordSRV and ChatChat and you shouldn't create 2 channels with the same ID in DiscordSRV. If you're still encountering this issue, please let us know by reopening the ticket.
